### ISSUE TITLE
Templates for tags and categories

### ISSUE THREAD

**Issue by digitalcraftsman** [dplesca/purehugo#10]
I would be great if you could add a template that lists the categories and tags of blog post under `example.com/tags` and `example.com/categories` in the style of your theme.

**Comment by dplesca** [comment]
I'm not sure I understand why would this be useful. Can you show me an example on a live website that does this?

**Comment by digitalcraftsman** [comment]
There's not really an example live. While reviewing a handful of themes for the [upcomming theme gallery](https://github.com/spf13/hugoThemesitescript) I saw this in the demo of your theme:

![](https://i.imgur.com/kp9wp1K.png)

**Comment by dplesca** [comment]
Oh, that's just the files server using hugo's server command. Normally Apache or nginx (if you were to use them) block access to a folder. I'm going to close this for now as I don't know if the majority of users will use `hugo server` to serve the files.
