### ISSUE TITLE
img-responsive

### ISSUE THREAD

**Issue by cirpo** [dplesca/purehugo#11]
"Reponsive Images
For responsive images you could use the built-in responsive image shortcode:
{{%/* img-responsive http://example.com/image.jpg */%}}" 

I tried as it's stated in the README but nothing happens, I can just see the plain text `{{%/* img-responsive http://example.com/image.jpg */%}}`.
I also tried to find any reference in Hugo code/doc about img-responsive but with no luck.
 Am I missing anything? Thanks

**Comment by dplesca** [comment]
I've made a small change to the readme file because it was indeed a bit misleading. The comments are there for the shortcode not to be executed on the upcoming themes site that uses the readme files to build its content. 

Anyway, basically you use the short code like this:
```go
{{% img-responsive "http://example.com/image.jpg" %}}
```
