### ISSUE TITLE
Unable to change date format for lists

### ISSUE THREAD

**Issue by igorkulman** [dplesca/purehugo#12]
I want to change the date format from 02 Jan 2006, 15:04 to 02 Jan 2006. If I change it in single.html, it works fine. If I change it in list.html, nothing happens. It looks like no matter what I change in list.html the changes are not not picked up.

**Comment by dplesca** [comment]
Hi,

Firstly, I want to thank you for taking the time to try the theme and opening a ticket with your problem.

I took a quick look and according to my view, the layouts are working like this:
- *layouts/index.html* - is responsible for the home page generation
- *layouts/_default/single.html* - single post page generation
- *layouts/_default/list.html* - categories/tags pages generation

Changing the date formatting on any one of these pages works as expected, but you should be looking for the right page. My guess is that you're modifying the list layout and looking at the homepage that is generated by the index layout. 

I'm going to close this for now, if you feel like I've missed anything feel free to re-open it.
