### ISSUE TITLE
Share links missing in Safari

### ISSUE THREAD

**Issue by feralbob** [dplesca/purehugo#20]
It looks like Safari isn't rendering the share links correctly.

![screen shot 2017-05-28 at 10 33 34 pm](https://cloud.githubusercontent.com/assets/8114/26533949/bb4c600c-43f5-11e7-998d-813448449bf7.png)

Compared to Chrome (Version 58.0.3029.110 (64-bit))
![screen shot 2017-05-28 at 10 34 32 pm](https://cloud.githubusercontent.com/assets/8114/26533969/daa80b72-43f5-11e7-8e65-615746af1ba7.png)

The links do appear to be in the HTML when viewed in the Safari debugger
![screen shot 2017-05-28 at 10 35 47 pm](https://cloud.githubusercontent.com/assets/8114/26533987/09a19b28-43f6-11e7-938c-4e36e7611b83.png)

Any ideas what the cause might be?

**Comment by dplesca** [comment]
Hi. This is weird. I've been testing it on Safari and everything seems ok. I'm on: `Version 10.1.1 (11603.2.5)`. Maybe an adblock is at fault?

**Comment by feralbob** [comment]
@dplesca  - You're correct. It was an Adblocker. Please accept my apologies...
