### ISSUE TITLE
error while building site

### ISSUE THREAD

**Issue by sambhav2612** [dplesca/purehugo#22]
I was trying to build my site with this theme. it worked fine until I hadn't added any page but as soon as I added a page using: `hugo new posts/welcome.md` and completed filling it with desired content, followed by running `hugo` then this error popped out:

```bash
Error while rendering "page": template: theme/_default/single.html:23:48: executing "theme/_default/single.html" at <.Params.categories>: range can't iterate over blog
```

please look through this.

**Comment by dplesca** [comment]
Hi. Can you please post the front matter for that page? I think that `categories` must be an array of strings, even if you have just one category.

**Comment by sambhav2612** [comment]
yes, it's working now. thanks.
