### ISSUE TITLE
Mixed Content in the README of Pure Hugo Theme on the Hugo website 

### ISSUE THREAD

**Issue by onedrawingperday** [dplesca/purehugo#29]
Hello @dplesca 

I am one of the people who maintain the [Hugo Themes](https://github.com/gohugoio/hugoThemes) repository.

Recently I [had a look](https://github.com/gohugoio/hugoThemes/issues/532) at the deploy log of the Hugo Themes website and it seems that you have entered an insecure `http://` URL in [line 57](https://github.com/dplesca/purehugo/blame/c075161bc6e1b919ad6198511709f522c1409180/README.md#L57) and [line 82](https://github.com/dplesca/purehugo/blame/c075161bc6e1b919ad6198511709f522c1409180/README.md#L82) of your theme's README.

This URL is throwing a browser warning about [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content):

        http://i.imgur.com/Dsj41Rz.png

Can you please change the above URL to `https`?

Thanks!

**Comment by dplesca** [comment]
That should be fixed by 7897071ec7f6379cf67a206d9f19c533a9e25c5c
