### ISSUE TITLE
PureHugo's Syntax Highlighting seems conflict with Hugo's inbuilt Highlighting

### ISSUE THREAD

**Issue by mattparkins** [dplesca/purehugo#30]
Love the theme.  The only part I can't get to work well is PureHugo's syntax highlighting which seems to conflict with Hugo's Chroma/Pygment Syntax Highlighting.

For instance the code in a .md file

    ``` bash
    alias trash="mv -t ~/.local/share/Trash/files --backup=t --verbose"
    ```

Is rendered literally with html tags in plain view:

    <span style="color:#24909d">alias</span> <span style="color:#40ffff">trash</span>=<span style="color:#ed9d13">"mv -t ~/.local/share/Trash/files --backup=t --verbose"</span>

...inside a black box, so it looks like two syntax highlighters are active.  I don't mind whether I disable yours or Hugo's, but how?

**Comment by mattparkins** [comment]
One workaround is to switch off Hugo's Syntax Highlighting of fenced code with 

    pygmentsCodefences = false

in your config.toml, although that means losing line numbering that Hugo's Chroma/Pygment supports.  I'd prefer to switch off PureHugo's Rainbow Syntax Highlighting.

**Comment by dplesca** [comment]
I'm thinking of disabling rainbow.js altogether, cause Chroma is probably good enough for most use cases.

**Comment by mattparkins** [comment]
Yeah, I think that probably makes sense.

**Comment by dplesca** [comment]
I have taken it out, can you please confirm it fixes your issue?

**Comment by mattparkins** [comment]
I can confirm this fixes the issue.  Thanks so much!

**Comment by mattparkins** [comment]
Ah, actually, I had to delete your syntax-highlighting css file and rebuild the css using your gulpfile - your syntax highlighting css file seemed to interfere with the highlighting for some reason when I changed from pygments back to Chroma?  (perhaps I did something wrong)

**Comment by dplesca** [comment]
Yeah, I'll have to remove that too, that makes sense.
