### ISSUE TITLE
{{ .Summary }} not working.

### ISSUE THREAD

**Issue by cbadhrinath** [dplesca/purehugo#33]
Currently planning to use this lovely theme for my new blog. 
On the Posts page, I wanted to show a summary of the post's description instead of the whole content.
As per [Hugo docs](https://gohugo.io/content-management/summaries/), changing the {{ .Content }} on _**list.html**_ to {{ .Summary }} and using  tag on my mark down is not working as expected. It still shows the whole description. Please let me know how to fix it. 
```
  <div class="post-description">
           {{ .Summary }}
  </div>
```

**Comment by positivejam** [comment]
I think you've made the right change but in the wrong place. Try making your change in `index.html` instead of `list.html`.

**Comment by cbadhrinath** [comment]
@positivejam Works as expected after changing it under index.html. Thanks. 👍🏽
