### ISSUE TITLE
javascript and css links didn't work when hosted on domain

### ISSUE THREAD

**Issue by fetmar** [dplesca/purehugo#6]
In header.html and footer.html, I had to change the 

    <link rel="stylesheet" href="{{ .Site.BaseUrl }}/css/all.min.css">
    ...
    <script src="{{ .Site.BaseUrl }}/js/all.min.js"></script>

to

    <link rel="stylesheet" href="{{ .Site.BaseUrl }}css/all.min.css">
    ...
    <script src="{{ .Site.BaseUrl }}js/all.min.js"></script>

The problem didn't show up until I uploaded it to my server and looked at it under the real domain name.

**Comment by dplesca** [comment]
Hm, I'm using purehugo on a couple of websites and haven't encountered this. How is your baseurl defined in your config file? For example for the demo site it's defined like below and it seems to be alright.

```toml
baseurl = "http://dplesca.github.io/purehugo/"
```

**Comment by fetmar** [comment]
Oh, that is strange, it's configured like this. `baseurl = "http://domain.name"`

I tried it with a trailing slash but I get two 404 requests. You know what? It might be an s3 problem for me. I'm seeing the 404 requests going to `http://domain.name//js/all.min.js` with two slashes after the domain name. Normally, I think that resolves to just one slash. At least in nginx and apache it does. I'll bet s3 works differently and is looking for a directory named "" or something.

**Comment by dplesca** [comment]
OK, I'll close this issue for now, if you encounter it again, feel free to re-open it.

**Comment by fetmar** [comment]
Hey man. Me again. fyi I had to do the same thing with the categories link in the list and single partials. they were coming out as `mydomain.com//categories/page`. Maybe there's a standard that I'm ignoring with a trailing slash in $baseUrl? I dunno. Same deal, works hosted locally with hugo, then doesn't when it's uploaded.

    # hugo version
    Hugo Static Site Generator v0.13 BuildDate: 2015-03-09T22:34:47-04:00

**Comment by dplesca** [comment]
OK, that is definitely weird. I am just going to try and replicate your problem. Outside of link without a trailing slash, do you have anything else about your setup I should know about? OS?

**Comment by ehammond** [comment]
This is a bug in hugo 0.13:

  https://github.com/spf13/hugo/issues/1105

It is fixed in the latest 0.14dev version if you compile hugo from GitHub source.

**Comment by dplesca** [comment]
@ehammond I've seen the discuss thread about it. I'm going to leave this open until hugo 0.14 is released.
