### ISSUE TITLE
Upgrade FontAwesome version and use recommended CDN

### ISSUE THREAD

**Issue by ehammond** [dplesca/purehugo#8]
FontAwesome is up to version 4.3.0, but purehugo uses 4.1.0, which is missing some icons I'd like to use.

[FontAwesome also recommends][fontawesome] using maxcdn.bootstrapcdn.com with this code:

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

It seems like using the recommended CDN might have a higher cache hit on users's browsers, speeding up the rendering.

Are there strong reasons for using version 4.1.0 or the netdna.bootstrapcdn.com CDN?

[fontawesome]: http://fontawesome.io/get-started/

**Comment by dplesca** [comment]
Hi, 

Thanks for the heads up. There is no reason for using the old version (or the link), that was just the version of font awesome when I last checked it. I'm pushing a change to fix as per your link right now.

**Comment by ehammond** [comment]
Thanks!
